---
- hosts: glusterfs-cluster
  vars:
  remote_user: X_USER_X
  tasks:
  - copy:
      src: tmp_hosts
      dest: /tmp/tmp_hosts
  - copy:
      src: gluster-volume.sh
      dest: /tmp/gluster-volume.sh
      mode: 0750
  - name: finding out number of host
    shell: hostname | sed 's/^.*[-]//' | sed 's/VM//'
    register: hostnumber
  - name: adding hosts to hosts file
    shell: cat /tmp/tmp_hosts
    register: hosts_line
  - name: add hosts to hostfile
    blockinfile:
      path: /etc/hosts
      block: |
        {{ hosts_line.stdout }}
    become: true
    become_user: root
  - file:
      path: /mnt/brick{{ hostnumber.stdout }}
      state: directory
      mode: 0755
    become: true
    become_user: root
  - name: create mdam volume over sdc and sdd
    shell: yes | mdadm --create md0 --level=0 --chunk=256K --raid-devices=2 /dev/sdc /dev/sdd
    become: true
    become_user: root
  - name: create mdam config file
    shell: mdadm --examine --scan | sudo tee /etc/mdadm.conf
    become: true
    become_user: root
  - name: create physical volume over raid set
    shell: pvcreate --dataalignment 1024K /dev/md/md0
    become: true
    become_user: root
  - name: create volume group
    shell: vgcreate --physicalextentsize 256K rhgs-data /dev/md/md0
    become: true
    become_user: root
  - name: create logical volume
    shell: lvcreate -L 1900g -T rhgs-data/brick{{ hostnumber.stdout }} -c 256K
    become: true
    become_user: root
  - name: format volume
    shell: mkfs.xfs -f -K /dev/rhgs-data/brick{{ hostnumber.stdout }}
    become: true
    become_user: root
  - name: add mountpoint to fstab
    blockinfile:
      path: /etc/fstab
      block: |
        /dev/rhgs-data/brick{{ hostnumber.stdout }}   /mnt/brick{{ hostnumber.stdout }}   xfs   defaults,inode64,nobarrier,noatime,nouuid 0 2
    become: true
    become_user: root
  - name: mount volumes
    shell: mount -a
    become: true
    become_user: root
  - name: configure gluster cluster
    shell: /tmp/gluster-volume.sh
    ignore_errors: True
    become: true
    become_user: root
