---
- hosts: glusterfs-cluster
  vars:
  remote_user: chris
  tasks:
  - copy:
      src: tmp_hosts
      dest: /tmp/tmp_hosts
  - name: adding hosts to hosts file
    shell: cat /tmp/tmp_hosts
    register: hosts_line
  - name: add hosts to hostfile
    blockinfile:
      path: /etc/hosts
      block: |
        {{ hosts_line.stdout }}
    become: true
    become_user: root
  - name: format disk C
    shell: mkfs.ext4 -L dataDiskC /dev/sdc
    become: true
    become_user: root
  - name: format disk D
    shell: mkfs.ext4 -L dataDiskD /dev/sdd
    become: true
    become_user: root
  - file:
      path: /mnt/datadisk1
      state: directory
      mode: 0755
  - file:
      path: /mnt/datadisk2
      state: directory
      mode: 0755
  - name: mount disk C to datadisk1
    shell: mount /dev/sdc /mnt/datadisk1
    become: true
    become_user: root
  - name: mount disk D to datadisk2
    shell: mount /dev/sdd /mnt/datadisk2
    become: true
    become_user: root
